services:
  - type: web
    name: mens-shop-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://mens-shop.vercel.app
      - key: CLIENT_URLS
        value: http://localhost:5173,https://mens-shop.vercel.app,https://mens-shop-bcnyemnew-maheshkumar09104s-projects.vercel.app
      - key: ADMIN_NAME
        value: Admin
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
